import json, os
from datetime import datetime

log_file = os.path.expanduser('~/demo_live_log.json')
with open(log_file, 'r') as f:
    logs = json.load(f)

txs = [l for l in logs if 'ETH' in l['mesaj']]
success = [t for t in txs if '✅' in t['mesaj']]
errors = [t for t in txs if '❌' in t['mesaj'] or 'hata' in t['mesaj'].lower()]

success_rate = (len(success) / len(txs) * 100) if txs else 0

timestamps = [datetime.fromisoformat(l['zaman'].replace('Z','+00:00')) for l in txs]
if len(timestamps) > 1:
    intervals = [(timestamps[i+1] - timestamps[i]).total_seconds() for i in range(len(timestamps)-1)]
    avg_interval = sum(intervals) / len(intervals)
else:
    avg_interval = 0

report = f"""# 📊 Mobil Uç Nokta Performans Raporu

**Tarih:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Ağ:** Base Sepolia (Android + Termux)
**Cihaz:** Tek Android telefon, CGNAT arkası, 42°C termal koruma

## 📈 Özet Metrikler

| Metrik | Değer |
|:---|:---|
| Toplam İşlem | {len(txs)} |
| Başarılı | {len(success)} |
| Başarısız | {len(errors)} |
| Başarı Oranı | %{success_rate:.1f} |
| Ortalama İşlem Aralığı | {avg_interval:.1f} saniye |
| Son İşlem Zamanı | {timestamps[-1].strftime('%H:%M:%S') if timestamps else 'N/A'} |

## 🔍 Teknik Notlar
- Tüm işlemler gerçek zincir üstü veridir, simülasyon değildir.
- Cihaz mobil CGNAT arkasında, dinamik IP rotasyonu mevcuttur.
- 42°C termal koruma limiti aktiftir.
- Bu rapor otomatik olarak üretilmiştir (Python + Termux).

---
*Generated by Mobile Edge QA Infrastructure | {datetime.now().strftime('%Y-%m-%d')}*
"""

with open('qa_report.md', 'w') as f:
    f.write(report)

print("✅ QA Raporu oluşturuldu: qa_report.md")
print(f"📊 {len(txs)} işlem, %{success_rate:.1f} başarı")
